name: AWS example workflow
on:
  workflow_dispatch:

env:
  AWS_REGION : "ca-central-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  AWSTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume:  arn:aws:iam::832570432760:role/github-drivebc-ca
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy with Terraform
        working-directory: infrastructure/aws/email/
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
